# Generated by Django 5.0.7 on 2024-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingslot_booking_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
