# Generated by Django 5.0.7 on 2024-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
