# Generated by Django 5.0.7 on 2024-08-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_employee_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
